---
title: "Convert Datasets"
output: html_notebook
---


```{r}
source(paste(project.R, "functions.R", sep = "/"))
```

## abrasion
```{r}
matfile <- "abrasion.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

abrasion <- matList$abrasion
hardness <- matList$hardness
tensile <- matList$hardness

savetoRda(abrasion, hardness, tensile, file = "abrasion.rda")
```

## bank
```{r}
matfile <- "bank.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

forge <- matList$forge
genuine <- matList$genuine

savetoRda(forge, genuine, file = "bank.rda")
```

## calibrat
```{r}
matfile <- "calibrat.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

counts <- matList$counts
tsh <- matList$tsh

savetoRda(counts, tsh, file = "calibrat.rda")

```

## cereal
```{r}
matfile <- "cereal.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

cereal <- matList$cereal

# deal with cell type
labs <- unlist(matList$labs)

savetoRda(cereal, labs, file = "cereal.rda")
```

## data
```{r}
matfile <- "data.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

X <- matList$X

# savetoRda(X, file = "data.mat")
```

## environmental
```{r}
matfile <- "environmental.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

Ozone <- matList$Ozone
SolarRadiation <- matList$SolarRadiation
Temperature <- matList$Temperature
WindSpeed <- matList$WindSpeed
comment <- matList$comment

savetoRda(Ozone, SolarRadiation, Temperature, WindSpeed, comment,
          file = "environmental.rda")
```

## ethanol
```{r}
matfile <- "ethanol.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

comment <- matList$comment
Compression <- matList$Compression
Equivalence <- matList$Equivalence
NOx <- matList$NOx

savetoRda(comment, Compression, Equivalence, NOx, file = "ethanol.rda")
```


## forearm
```{r}
matfile <- "forearm.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# names(matList)
forearm <- matList$forearm
savetoRda(forearm, file = "forearm.rda")
```

## galaxy
```{r}
matfile <- "galaxy.mat"

# matfilepath <- paste(project.extdata, matfile, sep = "/")
mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

EastWest <- matList$EastWest
NorthSouth <- matList$NorthSouth
Velocity <- matList$Velocity

savetoRda(EastWest, NorthSouth, Velocity, file = "galaxy.rda")
```

## geyser
```{r}
matfile <- "geyser.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

geyser <- matList$geyser
savetoRda(geyser, file = "geyser.rda")
```



## leukemia
```{r}
matfile <- "leukemia.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

btcell <- unlist(matList$btcell)         # unlist because object is a cell
cancertype <- unlist(matList$cancertype) # unlist because object is a cell
leukemia <- matList$leukemia

# deal with 51x2 cell
geneinfo <- unlist(matList$geneinfo)    # unlist because object is a cell
geneinfo.dim <- getCell.dim(mf, "geneinfo") # get dimensions of cell

geneinfo.col1 <- geneinfo[1:geneinfo.dim[1]]  # get 1st columns
geneinfo.col2 <- geneinfo[(geneinfo.dim[1]+1):length(geneinfo)] # get 2nd col

geneinfo.df <- data.frame(geneinfo.col1, geneinfo.col2) # create data frame
names(geneinfo.df) <- as.matrix(geneinfo.df[1, ])       # extract variable names
geneinfo.df <- geneinfo.df[-1, ]                        # remove row 1
rownames(geneinfo.df) <- NULL                           # reset row numbers
geneinfo <- geneinfo.df


savetoRda(btcell, cancertype, leukemia, geneinfo, file = "leukemia.rda")

```


## livestock
```{r}
matfile <- "livestock.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

comment       <- matList$comment
Count         <- matList$Count
Country       <- matList$Country
CountryName   <- unlist(matList$CountryName)
LivestockName <- unlist(matList$LivestockName)
LivestockType <- matList$LivestockType

savetoRda(comment,  
          Count,        
          Country,
          CountryName,
          LivestockName, 
          LivestockType,
          file = "livestock.rda"
)
```

## lsiex
```{r}
matfile <- "lsiex.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

docs    <- unlist(matList$docs)
termdoc <- matList$termdoc
words   <- matList$words
X       <- matList$X

savetoRda(docs,
          termdoc,
          words,  
          X,
          file = "lsiex.rda")
```

## lungA
```{r}
matfile <- "lungA.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

labA <- unlist(matList$labA)
lungA <- matList$lungA

savetoRda(labA, lungA, file = "lungA.rda")
```

## lungB

```{r}
matfile <- "lungB.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

labB <- unlist(matList$labB)
lungB <- matList$lungB

savetoRda(labB, lungB, file = "lungB.rda")
```

## matchbpm
```{r}
matfile <- "matchbpm.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

classlab <- matList$classlab
matchbpm <- matList$matchbpm

savetoRda(classlab, matchbpm, file = "matchbpm.rda")
```

## ochiaibpm
```{r}
matfile <- "ochiaibpm.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

classlab <- matList$classlab
ochiaibpm <- matList$ochiaibpm

savetoRda(classlab, ochiaibpm, file = "ochiaibpm.rda")
```

## oronsay
```{r}
matfile <- "oronsay.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

beachdune <- matList$beachdune
labcol <- unlist(matList$labcol)
midden <- matList$midden
oronsay <- matList$oronsay

savetoRda(beachdune,
          labcol,
          midden,
          oronsay,
          file = "oronsay.rda")

```

## ozone
```{r}
matfile <- "ozone.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)

comment <- matList$comment
Stamford <- matList$Stamford
Yonkers <- matList$Yonkers

savetoRda(comment, Stamford, Yonkers, file = "ozone.rda")
```

## playfair
```{r}
matfile <- "playfair.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
#saveMatlabVars()
```


## pollen
```{r}
matfile <- "pollen.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
saveMatlabVars()
```

## posse
```{r}
matfile <- "posse.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
saveMatlabVars()
```

## salmon
```{r}
matfile <- "salmon.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
saveMatlabVars()

```

## scurve
```{r}
matfile <- "scurve.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
saveMatlabVars()
```

## singer
```{r}
matfile <- "singer.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
saveMatlabVars()
```

## skulls
```{r}
matfile <- "skulls.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
```

## software
```{r}
matfile <- "software.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
```

## spam
```{r}
matfile <- "spam.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
```

## sparrow
```{r}
matfile <- "spam.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
```

## stockreturns
```{r}
matfile <- "stockreturns.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
saveMatlabVars()
```

## swissroll
```{r}
matfile <- "swissroll.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
saveMatlabVars()
```

## votfraud
```{r}
matfile <- "votfraud.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
saveMatlabVars()
```

## yeast
```{r}
matfile <- "yeast.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
saveMatlabVars()
```

## hamster
```{r}
matfile <- "hamster.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
saveMatlabVars()
```

## iradbpm
```{r}
matfile <- "iradbpm.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
saveMatlabVars()
```

## iris
```{r}
matfile <- "iris.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
saveMatlabVars()
```

## L1bpm
```{r}
matfile <- "L1bpm.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
# saveMatlabVars()
```

## sparrow
```{r}
matfile <- "sparrow.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
# saveMatlabVars(matfile, mf, matList)
# saveMatlabVars()
```

```{r}
matfile <- "livestock.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
```

```{r}
matfile <- "leukemia.mat"

mf <- matInfo(matfile)
mf

matList <- readMatfile(matfile)
```

## new function
```{r}
split.matlab.cell <- function(cell, columns) {
  cell.values <- get(cell)
  
}

split.matrix <- function(item, cols) {
  mat <- get(item)
  rows <- length(mat) / cols
  df.list <- split(as.data.frame(mat), rep(1:cols, each = rows))
  merged <- do.call("cbind", df.list)           # join the data frames in list
  names(merged) <- as.matrix(merged[1, ])       # extract variable names
  merged <- merged[-1, ]                        # remove row 1
  rownames(merged) <- 1:nrow(merged)                           # reset row numbers
  return(merged)
}


process.matlab.object <- function(item) {
  kls <- as.character(mf[mf$name == item, "class"]) # get object class
  size <- as.character(mf[mf$name == item,][1, 'size'])
  dim <- as.integer(unlist(strsplit(size, "x")))
  
  if (kls == "cell") {
    klass <- "cell"
    assign(item, as.matrix(unlist(matList[[item]])))  # unlist if cell    
    
    if ( (dim[2] >=2) & (dim[1] >= 2) ) {
      # stop("more than one column ...")
      cols <- min(dim[2], dim[1])
      cat("\tcell cols:", cols, "\t")
      assign(item, split.matrix(item, cols))
      #item.values <- get(item)
      #cat(class(item.values))
    }

  } else if (kls == "char") {
      assign(item, as.character(unlist(matList[[item]])))
      klass <- "char"
  } else if (kls == "double") {
      klass <- "double"
      assign(item, matList[[item]])
  } else {
      klass <- "else"
      assign(item, matList[[item]])
      
  }
    # get the object from the string
  obj <- get(item)
  dims <- ifelse(kls == "char", "NULL", paste(dim(obj), collapse = "x"))
  len <- ifelse(kls == "char", nchar(obj), length(obj))
  kls <- class(obj)
  to <- typeof(obj)
  stir <- capture.output(str(obj))[1]
  
  item.props <- list(Rname = item, dims = dims, length = len, Rclass = kls, 
                typeof = to, value = stir)
  item.whole <- list(values = obj, name = item, properties = item.props)
  return(item.whole)
}


# main
rdaFile <- paste(unlist(strsplit(matfile, "\\."))[1], "rda",sep = ".")
toSave <- NULL
rdf <- data.frame()

for (item in mf$name) {
  # cat(item, class(item), "\n")
  cat(item, "\t")
  #print(process.matlab.object(item)$Rname)
  
  # row <- process.matlab.object(item)
  whole <- process.matlab.object(item)
  assign(whole$name, whole$values)
  row <- whole$properties
  cat(row$Rclass, row$typeof)
  row.df <- data.frame(row, stringsAsFactors = FALSE)
  rdf <- rbind(row.df, rdf)
  cat("\n")
  toSave <- c(toSave, whole$name)
}   
rdf <- rdf[order(rdf[, 1]), ]
rownames(rdf) <- 1:nrow(rdf)
rdf
toSave
savetoRda(list = toSave, file = rdaFile)
```







## old function
```{r}
  rdaFile <- paste(unlist(strsplit(matfile, "\\."))[1], "rda",sep = ".")
  toSave <- NULL
  rdf <- data.frame()

  for (item in mf$name) {
    # item <- as.character(item)   # convert to character
    cat(item)
    kls <- as.character(mf[mf$name == item, "class"]) # get object class
    size <- as.character(mf[mf$name == item,][1, 'size'])
    dim <- as.integer(unlist(strsplit(size, "x")))
    cat(" ", kls, dim)
    
    if (kls == "cell") {
      # a Matlab cell is equivalent to a R matrix
      # print("Matlab cell")
      if (dim[2] & dim[1] > 1) stop("more than one column ...")
      assign(item, as.matrix(unlist(matList[[item]])))  # unlist if object is a cell
    } else if (kls == "char") {
      print("char vector")
      assign(item, as.character(unlist(matList[[item]]))[1])
      
    } else {
      assign(item, matList[[item]])
    }
    
    cat(class(get(item)))   # get the class before passing to function
    toSave <- c(toSave, item)
    row <- data.frame(getObject.info(item), stringsAsFactors = FALSE)
    rdf <- rbind(row, rdf)
    cat("\n")
    
  }
  rdf <- rdf[order(rdf[, 1]), ]
  # toSave
  savetoRda(list = toSave, file = rdaFile)
  rdf
```


```{r}
getObject.info <- function(item) {
  obj <- get(item)
  stir <- capture.output(str(obj))[1]
  dims <- paste(dim(obj), collapse = "x")
  len <- length(obj)
  kls <- class(obj)
  to <- typeof(obj)
  #cat(item, class(get(item)), "\n")
  list(Rname = item, dims = dims, 
       length = len, Rclass = kls, typeof = to)
}

#data.frame(getObject.info(item))
df <- data.frame()
for (item in toSave) {
  #print(item)
  row <- data.frame(getObject.info(item), stringsAsFactors = FALSE)
  df <- rbind(row, df)
}

df[order(df[, 1]), ]
#df

```




```{r}
#item
obj <- get(item)
capture.output(str(obj))[1]
paste(dim(obj), collapse = "x")
length(obj)
class(obj)
typeof(obj)
```




```{r}
# provide the Matlab file name
# stop if Matlab file does not exist
# get info from the Matlab file using RcppOctave


# read the Matlab file from R
# load the Matlab file results to a list

# iterate through objects in data frame returned from RcppOctave
  # convert object name item to character
  # get the class and dimension for current object
  # if class is `cell` 
  #   stop if any of the dimension of cell is greater than 1
  #   unlist the object before assigning to a var
  #   otherwise assign the object to a var with `assign`
  # collect the variable names to save later

# save the objects as .rda file

# create data frame of new objects in R
# show data frame of objects in Matlab and R

```


```{r}
myobj <- structure(list(a = 1, b = 2), class = "myclass")
print.myclass <- function(x, ...) cat("A: ", x$a, " B: ", x$b, "\n", sep = "")
myobj
```


```{r}
## split a 20x5 matrix into five 4x5 matrices 
xmat <- matrix(1:100, nrow=20, ncol=5, byrow=TRUE) 
xsplit <- rep( 1:5, times= rep(4, 5)) 
tmp <- split.data.frame(xmat, xsplit)
# xmat.new <- data.frame(tmp)
# xmat.mat <- data.matrix(xmat.new)
```

```{r}
## split a 100x1 matrix into five 50x2 matrices 
xmat2 <- matrix(1:100, nrow=100, ncol=1, byrow=TRUE) 
xsplit2 <- rep(1:2, times = rep(50, 2)) 
tmp2 <- split.data.frame(xmat2, xsplit2)
names(tmp2)
```

```{r}
split.matrix <- function(mat, cols) {
  rows <- length(mat) / cols
  df.list <- split(as.data.frame(mat), rep(1:cols, each = rows))
  merged <- do.call("cbind", df.list)           # join the data frames in list
  names(merged) <- as.matrix(merged[1, ])       # extract variable names
  merged <- merged[-1, ]                        # remove row 1
  rownames(merged) <- 1:nrow(merged)                           # reset row numbers
  return(merged)
}



geneinfo.cell <- split.matrix(geneinfo, 2)


```




```{r}
xmat0 <- geneinfo
split(as.matrix(xmat0), rep(1:2, each = 51))
```


```{r}
# a. 2 matrices which the first one consists of the first 500 rows, and the
# second one consist of the last 500 rows
xmat3 <- as.matrix(rnorm(100, 1, 0.5))
split(as.data.frame(xmat3), rep(1:2, each = 50))
```

```{r}
#  b. split the matrix equally and sequentially (according to the order of the
#  rows) into say 10 matrices with 100 x 4 dimension
split(as.data.frame(xmat3), rep(1:10, each = 100))
```

```{r}
split(as.data.frame(xmat3)[sample(1:nrow(xmat3)),], rep(1:10, each = 100))
```

```{r}
# split in ten matrices of 100 elements each
split(as.matrix(xmat3), rep(1:10, each = 100))
```

