---
title: "R Notebook"
output: html_notebook
---

```{r}
library(RcppOctave)
.CallOctave("version")
```

```{r}
loader <- OctaveFunction("
function [DF] = readMatfile()
  clear
  load('leukemia.mat')
  DF = whos();
end")
```


```{r}
ld <- loader()
names(ld)
```

```{r}
ld$name
ld$size
ld$bytes
ld$class
```

```{r}
df <- data.frame(ld$name, ld$bytes, ld$class)
```

```{r}
size <- ld$size
sapply(size, `[[`, 1)
sapply(size, `[[`, 2)
```

```{r}
paste(sapply(size, `[[`, 1), sapply(size, `[[`, 2), sep = "x")
```


```{r}
# convert to data frame
sz <- paste(sapply(ld$size, `[[`, 1), sapply(ld$size, `[[`, 2), sep = "x")
df <- data.frame(name = ld$name, size = sz, bytes = ld$bytes, class = ld$class)
df
```

```{r}
library(RcppOctave)

o.loader <- OctaveFunction("
function [struct] = readMatfile(mfile)
  load(mfile)
  struct = whos();
end
")

matInfo <- function(matFile) {
  ld <- o.loader(matFile)
  sz <- paste(sapply(ld$size, `[[`, 1), sapply(ld$size, `[[`, 2), sep = "x")
  df <- data.frame(name = ld$name, size = sz, bytes = ld$bytes, class = ld$class)
  return(df)
}

```

```{r}
mat <- paste(project.extdata, "abrasion.mat", sep = "/")
# l2 <- ldr(mat)
matInfo(mat)
```









```{r}

mat <- 'leukemia.mat'
ldr(mat)
```

```{r}
getwd()
```

