library(R.matlab)
library(RcppOctave)

readMatfile <- function(matfile, folder = project.extdata, verbose = FALSE) {
  matfileLong <- paste(folder, matfile, sep = "/")
  ret <- readMat(matfileLong, fixNames = FALSE)
  if (verbose) print(str(ret))
  return(ret)
}

savetoRda <- function(..., file, folder = project.data) {
  rdafileLong <- paste(folder, file, sep = "/")
  save(..., file = rdafileLong)
}

#' load .mat file in Octave
#' and get basic info
o.loader <- OctaveFunction("
function [struct] = readMatfile(mfile)
  load(mfile)
  clear mfile;
  struct = whos();
end
")

#' get information of .mat file objects
#' as a data frame
matInfo <- function(matfile) {
  matfilepath <- paste(project.extdata, matfile, sep = "/")
  ld <- o.loader(matfilepath)
  if (typeof(ld$size) == 'list') {
    sz <- paste(sapply(ld$size, `[[`, 1), sapply(ld$size, `[[`, 2), sep = "x")
  } else {
    sz <- paste(sapply(ld$size, `[[`, 1), collapse = "x")
  }
  # sz <- paste(sapply(ld$size, `[[`, 1), sapply(ld$size, `[[`, 2), sep = "x")
  df <- data.frame(name = ld$name, size = sz, bytes = ld$bytes, class = ld$class)
  df <- df[order(df[, 1]), ]
  rownames(df) <- NULL
  return(df)
}

#' get the dimensions of an object in a Matlab .mat file
#' It will return a vector of integers
#' Uses a data frame generated by matInfo()
getCell.dim <- function(df, cellName) {
  size <- as.character(df[df$name == cellName,][1, 'size'])
  dim <- as.integer(unlist(strsplit(size, "x")))
  return(dim)
}
